spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanager
    username: root
    password:
#    continueOnError: true
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
# Random Comment


surfline:

  url: https://services.surfline.com/kbyg


logging:
  file:
    name: ./log/demo-app.log
